apiVersion: v1
kind: Service
metadata:
  labels:
    app: dnb-ui
  name: dnb-ui
spec:
  type: NodePort
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: dnb-ui
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dnb-ui
  name: dnb-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnb-ui
  template:
    metadata:
      labels:
        app: dnb-ui
    spec:
      containers:
        - image: nodeshift/dnb-ui:latest
          imagePullPolicy: Always
          name: dnb-ui
          ports:
            - containerPort: 8080
              protocol: TCP
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: dnb-ui
  name: dnb-ui
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: dnb-ui
    weight: 100